version: "3"
services:
  nginx:
    image: nginx:1.21.6
    container_name: 'nginx'
    ports:
    - '8080:80'
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - nodejs
  nodejs:
    image: "node:lts-alpine3.17"
    container_name: 'node'
    working_dir: /app
    restart: always
    volumes:
        - ./src:/app
    entrypoint: ['npm', 'start']
    depends_on:
     ["mysql"]
  mysql:
    image: mysql
    container_name: 'mysql'
    volumes:
        - ./init.sql:/data/application/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: fullcycle
